url: https://adpawel.github.io
baseurl:

# Site settings
title: Paweł Adamczyk-strona główna
email: adamczyk@student.agh.edu.pl
description: "Official description"

# Team names, titles and social links
people:

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: instagram
      url: https://www.instagram.com/pavv_ada/?igshid=M2RkZGJiMzhjOQ%3D%3D&fbclid=IwAR1Xf0V-GC1yDcy_xtqQrQflIRCzdkLt8r7L0UxoCLMH4gOMgovdkyuGIg0
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100022730723736&sk=about
    

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/pavv_ada/?igshid=M2RkZGJiMzhjOQ%3D%3D&fbclid=IwAR1Xf0V-GC1yDcy_xtqQrQflIRCzdkLt8r7L0UxoCLMH4gOMgovdkyuGIg0
  - title: facebook
    url: https://www.facebook.com/profile.php?id=100022730723736&sk=about
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/adpawel

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty